language: node_js
deploy:
  provider: pages
  gh-token:
    secure: "pnIRgLhPRWgy83LYk8Z6yNpMtsr9SOLHY6hlyH6VSq7zrKt7xwgXDCIB6RBJP552wAueX3La5FTFMvMbcp7WCvDDjDbPoM7MJrSBQInBWjoxQ6NMhDYgxZLOp1uuEwQd1vYLU72GSg9GnQK3FuLGVy5B0R7+Z/dQkBhEBqSS1FdcSVBRcf+82/YH+z50E4088wqo69+W74qCAIM70xqaJl/SpMh9AH1wulKmWAQXhMuBAUtOSuGx7TEkqjHAeAKn+yn7DWLUKQ5CfvV5VF/uMDQ5TFpDDEvFIGHzd2vQPV6osfSUgmS28ex0YoVJNvALHKXj3e4z5v8B54pJjla0EJgejaSDmDFjThdmJUElvawQsM06/glGhxu8g2djJAS+lLzhX4gtcjuH3X/S9DoTXxCV1v/25Cxie/AHiVBKvLZ/4VElEVEnhbihd4KBfp4EF859uuzqTCJeS3k/eBYKYJsO0hiLqP0VWhvicFwXZ18RZAkWNkOT+vDVwx80ivHxVjOivnzxu+vz5Yco34TnUCQ/L0D7eyXFfHndJh1nBAC9xEIjhBgABEeVJE37datmFqsnIn+Uj1q7Jg19Y2Lb9DtZ0yr+BA6Pa46cytn8HjLiI4jYC6JSTNIAtncmCFJj4UTNTdJNqiAdEjYhD7U3rs82Z6eU8fAFXPT/Q/VDYXo="

  skip_cleanup: true
  on:
    branch: master
