language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: nuwCOF3prUkrIMEUDsNgC7HfjlBdm7T9+ymaF87xyCv7uU9pUxneGLMKy7SRqxhALYuJjGbISO4kSUnOaVfBWpjJ2o6PgtSIqci9Yx2xP+x5vE82WRFZC2mKSyuAmsPTRqbxbdubTEBjnVCtVI3Jr0g25QtQwV2L5MEeWAd0puyS/z2NNxbvS4wKF+LQHSmbiAdWAsXt7OMefuPQCK3Sn2YAdDZN3e0Gw+d1tphtOtIBc2zsYa4R0GUEiR7vI3iWpLLE2HrS0Jk/NDj3zO/OlWku1trkXoeeTVdsLXFz1xs+sv787/MoDEgznewx80c2e/zV+EII/rl31MpjLARUA9y41eyRMiOEPOLmemd0Hox54OxPzakX/Oagel5FmguDnh/2SgSqDHtgah8muyrNLV+p/kQIN4YPwSess1VqXVcd4b68QIObtc6Li9CMrQ5d/NGtpJVyi+1R/9+1geMeMiRltiZTf8B4Skp66FVrmoVDTJCBENs9YHWJGJQ23Dt11L6KOa1SXnCApqpGvllacWQtnHfpIMNHkY1w3AYHNzyGcZJN+j5RfFFLs/fj9PCnKF6ie9+agrklK0M+kSdKuv7F4uawDlHJUNwRTVh8rV+SS2AMCLVFYiSr2cmIbq4JR6WZLPshVtwa52P3qAqkK4kQQ9TFgf7+c9gbRNMWvng=
  on:
    branch: master
