language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: XTtVdzOLO/8UcWkEfLaJ+JXFtPVhnfHrYGHm3kNu5pYxeq1fF6GwF31QfnQyD5ce5Bg7TLTW3oUudRnddy2gqcfwYZ3DPuuDX1vk2MPOn2Jm0j7nQuj7SsWbiD4lk704v8gBOExDOMdwDNE3j3AUKYitbcvRtA/mHz3KbJhXURKSzUDztQi5+Sv1Sz4ZeXjT1UeWabG/KXyB5K/bl2X4hwgPTfGSSQMMo9DzWfrc5KzunZn6EjnGnDxcTu9xwgcPDZqq4fQjIY5gcJEc/1LaoIHqv3ieJgiKkcCrP0Ox7xPr7htFw2qyPCfqy3wKZ9ouV3nqlUIZZd/UO2aBy5fqcKVlgaxQ21ojDrIeXmAH1F0FRgvp3p4mLqUxnc2x9z+ePibl5a6wdXZUchInhpnM1X3XcMFpoPIWAjs1vYaXAtAo/kJS8Z9+BgqB+sfLnCrR+GM55t84SVTVpt0RBM1UKgWnYVOuebgI3AN6VWbwJbs5/9ivrnugQr75ZBEJCvaVEfFqFlPDJvIil4/yhE+Wi/F1vlytugNd08S45RIZr0j4tx23qoDHgBTAGg6SepsRoZqIk2k3z/Zk5vKk3yyYhixNO7WcM0Qbe5D3cMTvEw3r8zwOrKeIPcKjxx1hVTJzMrGYgILGtpZ+tn7ChKtk4Le6oaO5QqSncS0cx96KCsA=
  on:
    branch: master
