language: node_js
deploy:
  provider: pages
  github_token:
    secure: "kHiEsCuJF/mT1kLNF9VXpQOcXm+Fki1FXk+ra9+R9l1wHYezm0Eajog+WnSqqHpMAwPaWHcLTbhV0dpi8yIcDG14b/Xd5zZRsm562LqUMW/SavMqFnZfYKwWGV7fo9GKF28f4cSxKbH9ocVicU0HKktS7WDZCMU2jJOEa3q+zJoKJu0By34aOvfyHUMGeNOHFBN8hYgdWpthun3s3pqEdCn6n6FS9a7CPr7D5zR7bonMf9eEDs0fWee0Azv/yXUA6wCFjJ5ARaorEb3IP23YEuPSZ0F3BilRqX32m+Z7Gu8p5HlklpBtNspzlVTZZiQLva3EEwBYMcSD4kcn71k27pnXwWw16N13EKCfwplFfpmMJRQmmRjT4mhY17tSeE+ysFpG225YGsZczDzQUxjOPaWghFqDVf/d6YZaueyuvBcZSfmvMb4rknDLFfzxgouLwHpIVizjmBrXuX9FAdR0a+wpOIGa3XvCh9e/8zIBtRjvQaQK6yFduuq3BJZ/D7/M0nbTtI0fEgfeoe4SjNkauUtXNVshzvwvJXsTt8k4vG4YPMdtR9Li8vS4Z6Azk7JgdjbImLSEdt7nbJVXky/BovhGdcgx45+aqIeP4BwBUofdED/x4pQW9foftvnYNzyCfpdciXSI5SEKzULmE3wyrqYmBuwe1Xw1ETb/9ZMynBM="
  skip_cleanup: true
  on:
    branch: master
