language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: Ke4vVb773YbNKEcIhdQfMBRyh8nrvDl+ogmANRvdWpzTpYnchw1i98aznw/idXIAayfYmzq3Cmj6InelAWCooeuoqnhD4fpcc/Rxah6sOS2cAOP7oFkTT70JaD2+CFY7ZWHsYnFjA42ih1LeKZnz0Ucz8WOncLoM5SObVtYj6yymyWgRCZmPIPMTJldksJLVW+5UOewgR/bWm/ujGoFSAOnbTyB4jgCOnUtis2JQzU4636/+cL4tskdseGzpE8JWImeBg73N5FdE+IhLz+gZ5HxTRhsbdFKhFQH+XO4BeTIIW//YU/quvSPE+c/eWY6zpUXVFEgxW9QEFW19MchO9pCKIM9hIyNzlWHZa8mCk2zNWrYcWTNd4OOJSp19ovbySz/aD8sbza/CgpGPTyDWnHrmpTuMQJEDq2IsgeoSA/yF7KL1G3z9zT+1rU/5GSYWD9+Nr5bKTAb7Wv93hRQjAmO8dF5Ef+HlO2tv9+wx0aZZefyzyIsnH/tl2sFt4R68okrXl3NgXju499AOwO4lDPMYbHOSIH1GXKbby2CUB1XaWYkoJuYK3bjpFzXluthCkjSSHohDLr6rN2J0sMw7/9qHaFXNZlvzadMnss20//Rvrw0ZcCxW8OEVxwbcCZv12aEvVV8G/ePxy7tP9s2zSbe6HGVBwkplz+I6t1gM/38=
  on:
    branch: master
