language: node_js
deploy:
  provider: pages
  github_token:
    secure: "sRrazDTYqsIq5WGo3IPbi0Po6Cr8bbSj75HuJvB7BJpW8R/J3/PF/y/dOGefD0FqUo5yWbY/NM9yqGRDW8ehZ85iG5kOcqg1MrTsL5K7mN0XxXTZ4CH+xgV2qLNxTB/8rFAZYCtxlgtoaK00E+q0JXa5AmZqHTjoPSwNGgaAj28Nu1WfdYPpR/g2jX8rFv36qlOFoIP42Wanoj6fYjpZuPjRI/m5X7TtyDcJjYBg0SkbAuZsUS2gYe9UrFCNWy08SEvnlZZftAKygyj50XTHac6Is6IH/lilFTK2t8u3wnXJeDgimGAVP7s+YEcNzdv1TiBmxp4NdgfKwLebn/2ln+sJFV5yKOd0yrtENlpkEJB9iZyDaWqBlZltPcewnHBc9uYwsFk9n60agBn52q+phctVdOK9iXkbueBgPZiGW5LZtA5ekt+k9MkE4RcbsMBPIEJKvQfmYGkzvSePvRaLR+BpyYU6rnpYI656/2VybHjJlJ1kF65n7eDLy8W8T0jAtFf68xq/+Pye0fHZsTdEHmE6To+5cfAVI+cHqmSGCrrKZkR9UZeC2YCQEvOyezr8EWJWjaePdLrklZxTrLeGoGHs9uclv3BLprq9gEz5Oa6qyAFjDqwzT3KmujbPn0oyLSbprEMS1EPlcjYFPXyWY05EqE2VDDFC21b4OYxyn1U="
  skip_cleanup: true
  on:
    branch: master
