language: node_js

deploy:
  provider: pages
    github_token:
      secure: BGHBnDlV7cWah3SfNllxZ9wXbNjrChQn37MWZvsqPv6EVIFwQ0qiImDbyks+bq/7ePeOuOB7EbUcq4JhKov+OiSRMvJwof/6ukzZCGU7m7hPuYq3i6DqgiHUptleVsaL9Im6sxLt03Q+FOyH8uht2d1FK8Kg27X1EaqfYFBRYpPEJa2AvVtpI7+xI0pNsbj96XOhtzrHiVdNun39tXCUqf4aVF2BDj0PdEFRsMClOFFj7j2fs2B20SHyCRRA4/BRrtTCvLeHKAl+p6vtgiWjb0rILVEZNVyJTDE8LvYoNXfXRBIo8enGCaC3RdKM1FgzC3utXORpX9YnAAwYOnsEyWT46FyueYzFKnkvdWryCY9msSga1NbYAr/O85xs5B/B5aASMbEWN7JWzWeAgCLGLFh0z67phZEoTEQ3uZffc0K1ay6SzHci7hJYen9LvSpfcGEPciJLVgH0wiuraUbWhhOYTgvN1YgEvSecb8HXWiSfAcoSt+GxVcVR39bIFUQWL5zDpSDESlF/0AnHil2mNWJV1Dun+7R/nm9NZT1R6ZfY+Aox2TiRjg1ItNSFwe2MLJaNHvU02FapMZg1LGMEs/7+lxCWvzDL/HOKClvYBDc2bAsvZAYgELhg0zF/Cpz+zQLzLMM/8ciLnZBR/Lxw2/rwt1tlypdH/jhZq97z+Nw=
  skip_cleanup: true
  on:
    branch: master
