language: node_js

env:
  global:
    secure: VoiEzG8ZPjSiINrZDokb98JQcCpaY11URIdx49XPLKVbH2ik1yR+59kwBTmhpwLC6biBJqFrFO5DjFzsYdtF8r+qQyVvr3b0cQ3v9QNYkMnKg2TJOQjf476wOo7RkIxz6PEwFjJxRdI02mO/IiTrEKg03qAJuRjhy5/DF0xlhbKbq8VvqImG1emfg7k8/3YTqN6g/QUmgO43AsVOB7OzseY5w1D8+9aEiJcdvmBm6zal+oO57ZjQNRE1xgPhO7NG9M3mfEtgvWQw/VxSTOkTmrnuM2/+zzEwp0nkb7RUpCMZ2WNQxMVt3+9ueUSuJui/CA/hO4obxw9n2KXS/rVxT0O+KK2LBC5/71tVDlwLQdo4fHTAmRI4cqi9usvi2arkgacoy/Qow3wi7UQZAlRvFqSsCY3MuotdPhzHCosthttBwkx2byxIonuO1Ijjv49qugQG9adh+U+j7/Y4ebk8ZpQW1Z2bwy+bLe5ouoyY3HIGbL/Eyug9XAosO4YFBj883jBI5wv/fWPu6TZTLkHE8PoiW5y18elXqJ30+oSISBhncN0v7vqH220DjIZ+dDG5mJ8w5nd/8On8XPpWsXbBW72zJj/yzNUWNwwUzW1i0h9wwaJoB17N0tjfL7BX0xTPWfjqhbQx0QVrD9uUIIyarjg8AYJpi8shvv2Lrt36qq0=

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master

