language: node_js

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "ge4d02JgD0sj3jvURsRdqrgpcaZTVy4Wd8Vr20WuvaCdsui7tFOoefuASjByKliRQsQ0SLGJFVHRrsbjGkAiIXnM25B/Tcwc4TsuPpC9kic5l+0DrtwI75zXJfmGElx/7FCJnzrMx7vEMAbQllKZGTAZe/r9rkuQK/sy0DItCB8H9F9sYx8ktY4ZpKoe9DIYIuxC6vJh78tMxU7FXnpFlP6Q7PhKes3iK+suKFbx5yROzapv0UYY33tu3SrcYoWRxLXrTlrqrgJh0pYJmj1N34U7xK8ls+UKH4bnefB1jAOmZHqmYwCp7QkfWyyOz7K/amp4pOqB+Im2Y4RJGqyGQivNp09CYlMU8cv0VCU/e2uIWBhVLxp4MnFMxhHEdG45/Xb198G1C3GdPWJisXAi52jnULnjbWVw5TnQa5nXm761PdPynjkZmpuVZatVn9E5XWbmsGbX79WM9b+uNZrpgPYLcBfAcVVLVlpqkKDr/vUZGOvNDdo2dUyC9+m53ifYhhbZe8b/HTjh5d+1DNJbvGBf9Xf9t0mH1MvLB9E3UmzYlBowQan1XEVWFj+amEdr9YsARVVc93WpkwiTKy78t/OSIqPdOcEwfjPcabjteMNgTzIbHtnVmA3F0l8m4nSWifTSRqg9BIF42a0Ml+pvFlI72Uz50+YHFqKpNYBzGuc="
  on:
    branch: master
